cd $env:USERPROFILE\Desktop\vxparser

# server.py dosyasini olustur - her satiri ayri ayri yaz
 $s = @()
 $s += "import os, sys, sqlite3, json, threading, time, logging"
 $s += "logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')"
 $s += "log = logging.getLogger('vxparser')"
 $s += ""
 $s += "PORT = int(os.environ.get('PORT', 10000))"
 $s += "DB_PATH = os.environ.get('DB_PATH', '/tmp/vxparser.db')"
 $s += "M3U_PATH = os.environ.get('M3U_PATH', '/tmp/playlist.m3u')"
 $s += "DATA_READY = False"
 $s += "STARTUP_ERROR = None"
 $s += "LOAD_TIME = 0"
 $s += ""
 $s += 'GROUP_ORDER = ["TR ULUSAL","TR HABER","TR BEIN SPORTS","TR SPOR","TR BELGESEL","TR SINEMA UHD","TR SINEMA","TR MUZIK","TR COCUK","TR YEREL","TR DINI","TR RADYO","DE DEUTSCHLAND","DE VIP SPORTS","DE VIP SPORTS 2","DE SPORT","DE AUSTRIA","DE SCHWEIZ","DE FILM","DE SERIEN","DE KINO","DE DOKU","DE KIDS","DE MUSIK","DE INFOTAINMENT","DE NEWS","DE THEMEN","DE SONSTIGE"]'
 $s += ""
 $s += 'GROUP_RULES = {"TR ULUSAL":["TRT 1","Show TV","Star TV","ATV","Kanal D","FOX TV","TV8","Tele1","Beyaz TV","TV 8.5","A2","Tabii","Gain","TV 100","Flash TV","Kanal 7","TGRT","TLC","D MAX","ERT"],"TR HABER":["Haber","CNN Turk","HABER","NTV","TRT Haber","Bloomberg","TVNET","A Haber","Benguturk","Haber Global"],"TR BEIN SPORTS":["beIN Sports","beIN SPORT","beIN","beIN 4K"],"TR SPOR":["Spor","A Spor","TRT Spor","TJK","S Sport","GS TV","FB TV","BJK TV"],"TR BELGESEL":["Belgesel","Nat Geo","Discovery","Animal","History","Yaban TV","BBC Earth"],"TR SINEMA UHD":["4K","UHD"],"TR SINEMA":["Film","Sinema","Cinema","Movie","DigiMAX","FilmBox","Dream TV"],"TR MUZIK":["Muzik","Kral TV","Kral Pop","Power TV","Power Turk","Number One","NR1"],"TR COCUK":["Cocuk","Cartoon","Disney","Nick","Minika","Baby TV","Pepee"],"TR YEREL":["Yerel"],"TR DINI":["Dini","Din","Diyanet","Semerkand","Hilal","Lalegul"],"TR RADYO":["Radyo","Radio","FM"],"DE DEUTSCHLAND":["ARD","ZDF","Das Erste","WDR","NDR","BR ","SWR","HR ","MDR","RBB","Phoenix","3sat","KiKA","ONE","Arte"],"DE VIP SPORTS":["Sky Sport","Sky Bundesliga","Eurosport","DAZN","Sport1"],"DE VIP SPORTS 2":["Sky Sport Austria","Telekom Sport","Magenta Sport"],"DE SPORT":["Sport ","Eurosport","Sportdigital","Motorvision"],"DE AUSTRIA":["ORF","Puls 4","Servus"],"DE SCHWEIZ":["SRF","Swiss"],"DE FILM":["Sky Cinema","RTL+","13th Street","AXN","TNT Serie","TNT Film"],"DE SERIEN":["Serie","RTL","Sat.1","ProSieben","VOX","kabel eins","RTL2","Super RTL","Sixx","TELE 5"],"DE KINO":["Kino"],"DE DOKU":["Doku","Docu","D-MAX","N24 Doku","Spiegel TV"],"DE KIDS":["Kind","Kids","Toggo"],"DE MUSIK":["Musik","VIVA","Deluxe Music"],"DE INFOTAINMENT":["Info","N24","WELT","n-tv","BBC World","France 24"],"DE NEWS":["News","Tagesschau"],"DE THEMEN":["Shop","QVC","HSE","Bibel TV","Sonstig"]}'
 $s += ""
 $s += "def init_db():"
 $s += "    conn = sqlite3.connect(DB_PATH); c = conn.cursor()"
 $s += "    c.execute('CREATE TABLE IF NOT EXISTS categories(cid INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,sort_order INTEGER DEFAULT 9999)')"
 $s += "    c.execute('CREATE TABLE IF NOT EXISTS channels(lid INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,grp TEXT DEFAULT '''',cid INTEGER DEFAULT 0,logo TEXT DEFAULT '''',url TEXT DEFAULT '''',sort_order INTEGER DEFAULT 9999)')"
 $s += "    c.execute('CREATE INDEX IF NOT EXISTS idx_ch_cid ON channels(cid)')"
 $s += "    conn.commit(); conn.close(); log.info('DB baslatildi')"
 $s += ""
 $s += "def fetch_vavoo_channels():"
 $s += "    import httpx"
 $s += "    base_url = os.environ.get('VAVOO_BASE_URL', '')"
 $s += "    if not base_url: log.warning('VAVOO_BASE_URL yok!'); return False"
 $s += "    try:"
 $s += "        log.info('Vavoo cekiliyor: %s', base_url)"
 $s += "        with httpx.Client(timeout=120.0, verify=False, follow_redirects=True) as client:"
 $s += "            resp = client.get(base_url); resp.raise_for_status(); data = resp.json()"
 $s += "        channels_data = data.get('channels', data.get('streams', data.get('live', [])))"
 $s += "        if not channels_data and isinstance(data, list): channels_data = data"
 $s += "        if not channels_data: log.error('Kanal verisi yok'); return False"
 $s += "        conn = sqlite3.connect(DB_PATH); c = conn.cursor(); added = 0"
 $s += "        for ch in channels_data:"
 $s += "            if isinstance(ch, dict):"
 $s += "                name = ch.get('name', ch.get('title', ch.get('channel', '')))"
 $s += "                url = ch.get('url', ch.get('stream', ch.get('src', '')))"
 $s += "                logo = ch.get('logo', ch.get('icon', ''))"
 $s += "                group = ch.get('group', ch.get('category', ''))"
 $s += "                cat_id = ch.get('cat_id', ch.get('cid', 0))"
 $s += "            elif isinstance(ch, (list, tuple)) and len(ch) >= 3:"
 $s += "                name, url, group = str(ch[0]), str(ch[1]), str(ch[2])"
 $s += "                logo, cat_id = '', 0"
 $s += "            else: continue"
 $s += "            if not name or not url: continue"
 $s += "            if url.startswith('//'): url = 'https:' + url"
 $s += "            elif not url.startswith(('http://', 'https://')): url = 'https://' + url"
 $s += "            c.execute('INSERT OR REPLACE INTO channels(name,grp,cid,logo,url,sort_order) VALUES(?,?,?,?,?,?)', (name, group, cat_id, logo, url, 9999))"
 $s += "            added += 1"
 $s += "        conn.commit(); conn.close(); log.info('%d kanal eklendi', added); return True"
 $s += "    except Exception as e: log.error('Cekme hatasi: %s', e); return False"
 $s += ""
 $s += "def filter_tr_de():"
 $s += "    conn = sqlite3.connect(DB_PATH); c = conn.cursor()"
 $s += "    c.execute('SELECT COUNT(*) FROM channels'); total = c.fetchone()[0]"
 $s += "    kw = ['TRT','Show','Star TV','ATV','Kanal D','FOX','TV8','Tele1','Beyaz','Flash','Kanal 7','TGRT','Haber','CNN','NTV','Bloomberg','TVNET','A Haber','Benguturk','Haber Global','Spor','TJK','beIN','bein','S Sport','GS TV','FB TV','BJK TV','Fenerbahce','Galatasaray','Belgesel','Nat Geo','Discovery','Animal','History','Yaban','BBC Earth','4K','UHD','Film','Sinema','Cinema','Movie','DigiMAX','FilmBox','Magic','Yesilcam','Dream','Muzik','Kral','Power','Number One','NR1','Cocuk','Cartoon','Disney','Nick','Minika','Baby TV','Pepee','Yerel','Dini','Din','Diyanet','Semerkand','Hilal','Lalegul','Radyo','Radio','FM','ARD','ZDF','WDR','NDR','BR ','SWR','HR ','MDR','RBB','Phoenix','3sat','KiKA','Arte','RTL','Sat.1','ProSieben','VOX','kabel','RTL2','Super RTL','Sixx','TELE 5','Sky','Sport1','Eurosport','DAZN','Sportdigital','Motorvision','ORF','SRF','Servus','Puls','Schweiz','Austria','Swiss','Fox ','AXN','TNT','Universal','Boomerang','Comedy Central','Doku','D-MAX','Spiegel','Geo ','N24','WELT','n-tv','BBC World','France 24','QVC','HSE','Bibel','Shop','Magenta','Telekom','Tagesschau','Das Erste','ONE','13th Street']"
 $s += "    c.execute('SELECT lid, name, grp FROM channels')"
 $s += "    to_del = [r[0] for r in c.fetchall() if not any(k.lower() in (r[1]+' '+r[2]).lower() for k in kw)]"
 $s += "    if to_del: c.execute('DELETE FROM channels WHERE lid IN ('+','.join('?'*len(to_del))+')', to_del)"
 $s += "    conn.commit(); c.execute('SELECT COUNT(*) FROM channels'); remaining = c.fetchone()[0]; conn.close()"
 $s += "    log.info('Filtre: %d -> %d kanal (%d silindi)', total, remaining, len(to_del))"
 $s += ""
 $s += "def remap_groups():"
 $s += "    conn = sqlite3.connect(DB_PATH); c = conn.cursor()"
 $s += "    c.execute('DELETE FROM categories'); c.execute(\"UPDATE channels SET cid=0, grp=''\"); conn.commit()"
 $s += "    for idx, gn in enumerate(GROUP_ORDER):"
 $s += "        c.execute('INSERT OR IGNORE INTO categories(cid,name,sort_order) VALUES(?,?,?)', (idx+1, gn, idx+1))"
 $s += "    conn.commit(); c.execute('SELECT lid, name FROM channels'); updated = 0"
 $s += "    for lid, name in c.fetchall():"
 $s += "        assigned = False"
 $s += "        for gi, gn in enumerate(GROUP_ORDER):"
 $s += "            for kw in GROUP_RULES.get(gn, []):"
 $s += "                if kw.lower() in name.lower():"
 $s += "                    c.execute('UPDATE channels SET cid=?,grp=?,sort_order=? WHERE lid=?', (gi+1, gn, gi+1, lid))"
 $s += "                    updated += 1; assigned = True; break"
 $s += "            if assigned: break"
 $s += "        if not assigned:"
 $s += "            c.execute(\"SELECT cid FROM categories WHERE name='DE SONSTIGE'\")"
 $s += "            row = c.fetchone()"
 $s += "            if row: c.execute(\"UPDATE channels SET cid=?,grp='DE SONSTIGE',sort_order=9998 WHERE lid=?\", (row[0], lid))"
 $s += "    conn.commit(); conn.close(); log.info('Grup remap: %d kanal', updated)"
 $s += ""
 $s += "def generate_m3u():"
 $s += "    conn = sqlite3.connect(DB_PATH); conn.row_factory = sqlite3.Row; c = conn.cursor()"
 $s += '    c.execute("SELECT c.name,c.url,c.logo,COALESCE(cat.name,\'Sonstige\') as group_name FROM channels c LEFT JOIN categories cat ON c.cid=cat.cid ORDER BY COALESCE(cat.sort_order,9999),c.name")'
 $s += "    lines = ['#EXTM3U']"
 $s += '    for ch in c.fetchall(): lines.append(\'#EXTINF:-1 tvg-logo=\"\'+str(ch[\"logo\"] or \"\")+\'\" group-title=\"\'+str(ch[\"group_name\"])+\'\",\'+str(ch[\"name\"]))'
 $s += "    lines.extend([ch['url'] for ch in c.fetchall()])"
 $s += "    conn.close()"
 $s += "    with open(M3U_PATH, 'w', encoding='utf-8') as f: f.write(chr(10).join(lines))"
 $s += "    log.info('M3U uretildi')"
 $s += ""
 $s += "def startup_sequence():"
 $s += "    global DATA_READY, STARTUP_ERROR; start = time.time()"
 $s += "    try:"
 $s += "        log.info('=== VxParser Baslangic ==='); init_db()"
 $s += "        if os.environ.get('VAVOO_BASE_URL'): fetch_vavoo_channels()"
 $s += "        else: log.warning('VAVOO_BASE_URL yok!')"
 $s += "        filter_tr_de(); remap_groups(); generate_m3u()"
 $s += "        LOAD_TIME = time.time() - start; DATA_READY = True"
 $s += "        log.info('=== Hazir! (%.1fs) ===', LOAD_TIME)"
 $s += "    except Exception as e: STARTUP_ERROR = str(e); log.error('Hata: %s', e)"
 $s += ""
 $s += "def main():"
 $s += "    log.info('VxParser baslatiliyor...')"
 $s += "    threading.Thread(target=startup_sequence, daemon=True).start()"
 $s += "    import uvicorn; from video import app"
 $s += "    uvicorn.run(app, host='0.0.0.0', port=PORT)"
 $s += ""
 $s += 'if __name__ == "__main__": main()'
 $s | Set-Content -Path "server.py" -Encoding utf8
Write-Host "server.py OLUSTURULDU" -ForegroundColor Green
