cd $env:USERPROFILE\Desktop\vxparser

 $v = @()
 $v += "import os, sqlite3, httpx, logging, threading"
 $v += "from fastapi import FastAPI, Query, HTTPException"
 $v += "from fastapi.responses import PlainTextResponse"
 $v += ""
 $v += "DB_PATH = os.environ.get('DB_PATH', '/tmp/vxparser.db')"
 $v += "M3U_PATH = os.environ.get('M3U_PATH', '/tmp/playlist.m3u')"
 $v += "app = FastAPI(title='VxParser IPTV Proxy', version='2.0.0')"
 $v += ""
 $v += "def get_db():"
 $v += "    conn = sqlite3.connect(DB_PATH); conn.row_factory = sqlite3.Row; return conn"
 $v += ""
 $v += "@app.get('/')"
 $v += "async def root():"
 $v += "    import server"
 $v += "    return {'status': 'ready' if server.DATA_READY else 'loading', 'message': 'Hazir!' if server.DATA_READY else 'Kanallar yukleniyor, 30-60sn bekle...'}"
 $v += ""
 $v += "@app.get('/health')"
 $v += "async def health(): return {'status': 'ok'}"
 $v += ""
 $v += "@app.get('/get.php')"
 $v += "async def get_playlist(username: str = Query('admin'), password: str = Query('admin'), type: str = Query('m3u_plus'), output: str = Query('m3u_plus')):"
 $v += '    conn = get_db(); c = conn.cursor()'
 $v += "    c.execute('SELECT c.lid,c.name,c.url,c.logo,COALESCE(cat.name,\'Sonstige\') as group_name FROM channels c LEFT JOIN categories cat ON c.cid=cat.cid ORDER BY COALESCE(cat.sort_order,9999),c.name')"
 $v += "    channels = c.fetchall(); conn.close()"
 $v += "    lines = ['#EXTM3U url-tvg=\"\" deinterlace=\"1\"']"
 $v += '    for ch in channels: lines.append(\'#EXTINF:-1 tvg-id=\"\'+str(ch[\"lid\"])+\'\" tvg-logo=\"\'+str(ch[\"logo\"] or \"\")+\'\" group-title=\"\'+str(ch[\"group_name\"])+\'\",\'+str(ch[\"name\']))'
 $v += '    for ch in channels: lines.append(ch[\"url\"])'
 $v += "    return PlainTextResponse(content=chr(10).join(lines), media_type='audio/x-mpegurl')"
 $v += ""
 $v += "@app.get('/player_api.php')"
 $v += "async def player_api(username: str = Query('admin'), password: str = Query('admin'), action: str = Query(None)):"
 $v += "    conn = get_db()"
 $v += '    if action == "get_live_categories":'
 $v += "        c = conn.cursor(); c.execute('SELECT cid as category_id, name as category_name FROM categories ORDER BY sort_order')"
 $v += "        cats = [dict(r) for r in c.fetchall()]; conn.close(); return cats"
 $v += '    elif action == "get_live_streams":'
 $v += "        c = conn.cursor()"
 $v += "        c.execute('SELECT c.lid as stream_id,c.name as name,c.logo as stream_icon,c.cid as category_id,COALESCE(cat.name,\'Sonstige\') as category_name FROM channels c LEFT JOIN categories cat ON c.cid=cat.cid ORDER BY COALESCE(cat.sort_order,9999),c.name')"
 $v += "        streams = [dict(r) for r in c.fetchall()]; conn.close(); return streams"
 $v += "    else:"
 $v += "        c = conn.cursor(); c.execute('SELECT COUNT(*) FROM channels'); total = c.fetchone()[0]"
 $v += "        c.execute('SELECT COUNT(*) FROM categories'); cats = c.fetchone()[0]; conn.close()"
 $v += "        return {'user_info':{'username':username,'status':'Active','max_connections':1},'available_channels':total,'available_categories':cats}"
 $v += ""
 $v += "@app.get('/playlist.m3u')"
 $v += "async def download_playlist():"
 $v += "    conn = get_db(); c = conn.cursor()"
 $v += "    c.execute('SELECT c.name,c.url,c.logo,COALESCE(cat.name,\'Sonstige\') as group_name FROM channels c LEFT JOIN categories cat ON c.cid=cat.cid ORDER BY COALESCE(cat.sort_order,9999),c.name')"
 $v += "    lines = ['#EXTM3U']"
 $v += '    for ch in c.fetchall(): lines.append(\'#EXTINF:-1 tvg-logo=\"\'+str(ch[\"logo\"] or \"\")+\'\" group-title=\"\'+str(ch[\"group_name\"])+\'\",\'+str(ch[\"name\"]))'
 $v += '    for ch in c.fetchall(): lines.append(ch[\"url\"])'
 $v += "    conn.close()"
 $v += "    return PlainTextResponse(content=chr(10).join(lines), media_type='audio/x-mpegurl')"
 $v += ""
 $v += "@app.get('/reload')"
 $v += "async def reload_channels():"
 $v += "    import server; server.DATA_READY = False; server.STARTUP_ERROR = None"
 $v += "    def do_reload():"
 $v += "        try: server.init_db(); server.fetch_vavoo_channels(); server.filter_tr_de(); server.remap_groups(); server.generate_m3u(); server.DATA_READY = True"
 $v += "        except Exception as e: server.STARTUP_ERROR = str(e)"
 $v += "    threading.Thread(target=do_reload, daemon=True).start()"
 $v += "    return {'status':'reloading','message':'Yukleniyor... 30-60sn bekle'}"
 $v += ""
 $v += "@app.get('/stats')"
 $v += "async def stats():"
 $v += "    import server; conn = get_db(); c = conn.cursor()"
 $v += "    c.execute('SELECT COUNT(*) FROM channels'); total = c.fetchone()[0]"
 $v += "    c.execute('SELECT COUNT(*) FROM categories'); cats = c.fetchone()[0]"
 $v += "    c.execute('SELECT COALESCE(cat.name,\'Eslesmeyen\') as g, COUNT(*) as cnt FROM channels c LEFT JOIN categories cat ON c.cid=cat.cid GROUP BY c.cid ORDER BY MIN(cat.sort_order)')"
 $v += "    groups = [{'group':r[0],'count':r[1]} for r in c.fetchall()]; conn.close()"
 $v += "    return {'total_channels':total,'total_categories':cats,'groups':groups,'data_ready':server.DATA_READY}"
 $v | Set-Content -Path "video.py" -Encoding utf8
Write-Host "video.py OLUSTURULDU" -ForegroundColor Green
